# SPDX-License-Identifier: Apache-2.0
"""Tests for the dnsmasq fragment renderer."""

from pathlib import Path

from gwifi_netboot.identity import load_identity
from gwifi_netboot.render import render_dnsmasq

FIXTURE = Path(__file__).parent / "fixtures" / "pucks.json"

GOLDEN_ONE_ARMED = """\
# Generated by gwifi-netboot — puck identity + install arming. DO NOT EDIT.
# Arming: `gwifi-netboot arm <puck>`; state in /var/lib/gwifi-netboot.
dhcp-host=44:07:0b:01:87:b4,44:07:0b:01:87:b5,10.1.4.104,puck04
dhcp-host=44:07:0b:01:a2:21,44:07:0b:01:a2:22,10.1.4.112,puck12,set:install
dhcp-boot=tag:install,gale-installer.itb
"""

GOLDEN_NONE_ARMED = """\
# Generated by gwifi-netboot — puck identity + install arming. DO NOT EDIT.
# Arming: `gwifi-netboot arm <puck>`; state in /var/lib/gwifi-netboot.
dhcp-host=44:07:0b:01:87:b4,44:07:0b:01:87:b5,10.1.4.104,puck04
dhcp-host=44:07:0b:01:a2:21,44:07:0b:01:a2:22,10.1.4.112,puck12
"""


def pucks():
    return load_identity(FIXTURE)


def test_one_armed_golden():
    out = render_dnsmasq(pucks(), armed={"44:07:0b:01:a2:21"})
    assert out == GOLDEN_ONE_ARMED


def test_none_armed_no_dhcp_boot_line():
    out = render_dnsmasq(pucks(), armed=set())
    assert out == GOLDEN_NONE_ARMED
    assert "dhcp-boot" not in out


def test_single_combined_dhcp_host_line_per_puck():
    # NEVER two dhcp-host lines for the same MACs — dnsmasq's duplicate
    # handling is surprising and --test does not catch it.
    out = render_dnsmasq(pucks(), armed={"44:07:0b:01:a2:21"})
    assert out.count("44:07:0b:01:a2:21") == 1


def test_armed_by_either_mac():
    # Arming state is keyed by eth0, but tolerate eth1 keys too.
    out = render_dnsmasq(pucks(), armed={"44:07:0b:01:a2:22"})
    assert "puck12,set:install" in out


def test_deterministic():
    a = render_dnsmasq(pucks(), armed=set())
    b = render_dnsmasq(list(reversed(pucks())), armed=set())
    assert a == b


def test_empty_identity():
    out = render_dnsmasq([], armed=set())
    assert out.startswith("#")
    assert "dhcp-host" not in out
