#!/usr/bin/env python3
"""Authoritative CAPTURED branch coverage = union of the external-stimulus campaign
(coverage_captured.py -> tmp/cap_trace_cache.pkl) AND the direct function-invocation sweep
(fcall_sweep.py -> tmp/sweep_edges.pkl), measured over the validated rda denominator.

Both sources are genuine execution of the real captured firmware (external interfaces + direct
unit-test-style function calls); the union is the real reachable-and-executed coverage.
"""
import os
import pickle

import rda

HERE = os.path.dirname(os.path.abspath(__file__))
CAP = os.path.join(HERE, "..", "..", "gale-ec-gale_v1.1.5337-0115719-2026-06-04.bin")
TMP = os.path.join(HERE, "tmp")


def load(name):
    p = os.path.join(TMP, name)
    if not os.path.exists(p):
        return set(), set()
    with open(p, "rb") as f:
        return pickle.load(f)


def main():
    cexec, cedges = load("cap_trace_cache.pkl")
    sexec, sedges = load("sweep_edges.pkl")
    fexec, fedges = load("fuzz_edges.pkl")
    pexec, pedges = load("pdstate_edges.pkl")
    rexec, redges = load("printf_edges.pkl")
    mexec, medges = load("cmd_edges.pkl")
    uexec, uedges = load("pure_edges.pkl")
    texec, tedges = load("struct_edges.pkl")
    gexec, gedges = load("gfuzz_edges.pkl")
    dexec, dedges = load("disp_edges.pkl")
    nexec, nedges = load("never_edges.pkl")
    hexec, hedges = load("hook_edges.pkl")
    oexec, oedges = load("pdo_edges.pkl")
    vexec, vedges = load("div_edges.pkl")
    wexec, wedges = load("misc_edges.pkl")
    aexec, aedges = load("argsweep_edges.pkl")
    qexec, qedges = load("concolic_edges.pkl")
    yexec, yedges = load("pdfns_edges.pkl")
    zexec, zedges = load("rxdec_edges.pkl")
    bexec, bedges = load("usbep0_edges.pkl")
    kexec, kedges = load("pdhook_edges.pkl")
    ctexec, ctedges = load("contract_edges.pkl")
    vsexec, vsedges = load("vdmsrc_edges.pkl")
    tfexec, tfedges = load("txfail_edges.pkl")
    adexec, adedges = load("adcsweep_edges.pkl")
    coexec, coedges = load("console_edges.pkl")
    caexec, caedges = load("cmdargs_edges.pkl")
    haexec, haedges = load("hcargs_edges.pkl")
    rdexec, rdedges = load("rxdecode2_edges.pkl")
    fwexec, fwedges = load("fwupdate_edges.pkl")
    flexec, fledges = load("flashlock_edges.pkl")
    fpexec, fpedges = load("flashprog_edges.pkl")
    ieexec, ieedges = load("i2cevt_edges.pkl")
    ccexec, ccedges = load("ccstate_edges.pkl")
    pcexec, pcedges = load("pdcmd_edges.pkl")
    hpexec, hpedges = load("hostpkt_edges.pkl")
    psexec, psedges = load("pdsoak_edges.pkl")
    vtexec, vtedges = load("vdmtx_edges.pkl")
    dbexec, dbedges = load("debounce_edges.pkl")
    rqexec, rqedges = load("reqcap_edges.pkl")
    ssexec, ssedges = load("srcseq_edges.pkl")
    pnexec, pnedges = load("panic_edges.pkl")
    piexec, piedges = load("panicinject_edges.pkl")
    dqexec, dqedges = load("dmairq_edges.pkl")
    uvexec, uvedges = load("usbevt_edges.pkl")
    giexec, giedges = load("gpioirq_edges.pkl")
    siexec, siedges = load("smallisr_edges.pkl")
    tcexec, tcedges = load("tcpc_edges.pkl")
    syexec, syedges = load("sysinfo_edges.pkl")
    cmexec, cmedges = load("consmisc_edges.pkl")
    c2exec, c2edges = load("consmisc2_edges.pkl")
    c3exec, c3edges = load("consmisc3_edges.pkl")
    dfexec, dfedges = load("drpfree_edges.pkl")
    fxexec, fxedges = load("flashprot_edges.pkl")
    auexec, auedges = load("audioacc_edges.pkl")
    liexec, liedges = load("lib_edges.pkl")
    p2exec, p2edges = load("printf2_edges.pkl")
    sdexec, sdedges = load("spidma_edges.pkl")
    wpexec, wpedges = load("flashwp_edges.pkl")
    m4exec, m4edges = load("consmisc4_edges.pkl")
    swexec, swedges = load("pdswap_edges.pkl")
    feexec, feedges = load("flasherr_edges.pkl")
    ffexec, ffedges = load("flashfault_edges.pkl")
    dfexec2, dfedges2 = load("dmafault_edges.pkl")
    pcexec2, pcedges2 = load("protcall_edges.pkl")
    stexec, stedges = load("spitcif_edges.pkl")
    sbexec, sbedges = load("spibusy_edges.pkl")
    pkexec, pkedges = load("pdsink_edges.pkl")
    si2exec, si2edges = load("sysinfo2_edges.pkl")
    ggexec, ggedges = load("gpioget_edges.pkl")
    hvexec, hvedges = load("hcver_edges.pkl")
    rpexec, rpedges = load("recpd_edges.pkl")
    dtexec, dtedges = load("drptoggle_edges.pkl")
    pbexec, pbedges = load("pddbg_edges.pkl")
    ceexec, ceedges = load("conschar_edges.pkl")
    f2exec, f2edges = load("flashprot2_edges.pkl")
    obexec, obedges = load("optbclean_edges.pkl")
    fuexec, fuedges = load("pdfwupdate_edges.pkl")
    ps2exec, ps2edges = load("pdsrc_edges.pkl")
    biexec, biedges = load("pdbist_edges.pkl")
    csaexec, csaedges = load("consargs_edges.pkl")
    h2exec, h2edges = load("hcpkt2_edges.pkl")
    h3exec, h3edges = load("hccmd2_edges.pkl")
    iiexec, iiedges = load("i2cinit_edges.pkl")
    dwexec, dwedges = load("dmawait_edges.pkl")
    asexec, asedges = load("argshape_edges.pkl")
    executed = set(cexec) | set(sexec) | set(fexec) | set(pexec) | set(rexec) | set(mexec) | set(uexec) | set(texec) | set(gexec) | set(dexec) | set(nexec) | set(hexec) | set(oexec) | set(vexec) | set(wexec) | set(aexec) | set(qexec) | set(yexec) | set(zexec) | set(bexec) | set(kexec) | set(ctexec) | set(vsexec) | set(tfexec) | set(adexec) | set(coexec) | set(caexec) | set(haexec) | set(rdexec) | set(fwexec) | set(flexec) | set(fpexec) | set(ieexec) | set(ccexec) | set(pcexec) | set(hpexec) | set(psexec) | set(vtexec) | set(dbexec) | set(rqexec) | set(ssexec) | set(pnexec) | set(piexec) | set(dqexec) | set(uvexec) | set(giexec) | set(siexec) | set(tcexec) | set(syexec) | set(cmexec) | set(c2exec) | set(c3exec) | set(dfexec) | set(fxexec) | set(auexec) | set(liexec) | set(p2exec) | set(sdexec) | set(wpexec) | set(m4exec) | set(swexec) | set(feexec) | set(ffexec) | set(dfexec2) | set(pcexec2) | set(stexec) | set(sbexec) | set(pkexec) | set(si2exec) | set(ggexec) | set(hvexec) | set(rpexec) | set(dtexec) | set(pbexec) | set(ceexec) | set(f2exec) | set(obexec) | set(fuexec) | set(ps2exec) | set(biexec) | set(csaexec) | set(h2exec) | set(h3exec) | set(iiexec) | set(dwexec) | set(asexec)
    edges = set(cedges) | set(sedges) | set(fedges) | set(pedges) | set(redges) | set(medges) | set(uedges) | set(tedges) | set(gedges) | set(dedges) | set(nedges) | set(hedges) | set(oedges) | set(vedges) | set(wedges) | set(aedges) | set(qedges) | set(yedges) | set(zedges) | set(bedges) | set(kedges) | set(ctedges) | set(vsedges) | set(tfedges) | set(adedges) | set(coedges) | set(caedges) | set(haedges) | set(rdedges) | set(fwedges) | set(fledges) | set(fpedges) | set(ieedges) | set(ccedges) | set(pcedges) | set(hpedges) | set(psedges) | set(vtedges) | set(dbedges) | set(rqedges) | set(ssedges) | set(pnedges) | set(piedges) | set(dqedges) | set(uvedges) | set(giedges) | set(siedges) | set(tcedges) | set(syedges) | set(cmedges) | set(c2edges) | set(c3edges) | set(dfedges) | set(fxedges) | set(auedges) | set(liedges) | set(p2edges) | set(sdedges) | set(wpedges) | set(m4edges) | set(swedges) | set(feedges) | set(ffedges) | set(dfedges2) | set(pcedges2) | set(stedges) | set(sbedges) | set(pkedges) | set(si2edges) | set(ggedges) | set(hvedges) | set(rpedges) | set(dtedges) | set(pbedges) | set(ceedges) | set(f2edges) | set(obedges) | set(fuedges) | set(ps2edges) | set(biedges) | set(csaedges) | set(h2edges) | set(h3edges) | set(iiedges) | set(dwedges) | set(asedges)
    seeds = executed | rda.ptr_targets(os.path.abspath(CAP))
    insns, cond, calls = rda.analyze(os.path.abspath(CAP), extra_seeds=seeds)
    taken = set(a for a in cond if (a, cond[a][1]) in edges)
    nottaken = set(a for a in cond if (a, cond[a][0]) in edges)
    both = [a for a in cond if a in taken and a in nottaken]
    reached = [a for a in cond if a in executed]

    def bd(es):
        t = set(a for a in cond if (a, cond[a][1]) in es)
        n = set(a for a in cond if (a, cond[a][0]) in es)
        return len([a for a in cond if a in t and a in n])

    print("=== CAPTURED combined coverage (campaign + function-call sweep) ===")
    print("  rda branches (denominator): %d" % len(cond))
    print("  reached:        %d (%.1f%%)" % (len(reached), 100.0 * len(reached) / len(cond)))
    print("  both-dirs:      %d (%.1f%%)" % (len(both), 100.0 * len(both) / len(cond)))
    print("  campaign-only both-dirs: %d" % bd(cedges))
    print("  sweep-only both-dirs:    %d" % bd(sedges))
    print("  fuzz-only both-dirs:     %d" % bd(fedges))
    print("  pdstate-only both-dirs:  %d" % bd(pedges))
    print("  printf-only both-dirs:   %d" % bd(redges))
    print("  cmd-only both-dirs:      %d" % bd(medges))
    print("  pure-only both-dirs:     %d" % bd(uedges))
    print("  struct-only both-dirs:   %d" % bd(tedges))
    print("  gfuzz-only both-dirs:    %d" % bd(gedges))
    print("  disp-only both-dirs:     %d" % bd(dedges))
    print("  never-only both-dirs:    %d" % bd(nedges))
    print("  hook-only both-dirs:     %d" % bd(hedges))
    print("  pdo-only both-dirs:      %d" % bd(oedges))
    print("  div-only both-dirs:      %d" % bd(vedges))
    print("  misc-only both-dirs:     %d" % bd(wedges))
    print("  argsweep-only both-dirs: %d" % bd(aedges))
    print("  concolic-only both-dirs: %d" % bd(qedges))
    print("  pdfns-only both-dirs:    %d" % bd(yedges))
    print("  rxdec-only both-dirs:    %d" % bd(zedges))
    print("  usbep0-only both-dirs:   %d" % bd(bedges))
    print("  pdhook-only both-dirs:   %d" % bd(kedges))
    print("  contract-only both-dirs: %d" % bd(ctedges))
    print("  vdmsrc-only both-dirs:   %d" % bd(vsedges))
    print("  txfail-only both-dirs:   %d" % bd(tfedges))
    print("  adcsweep-only both-dirs: %d" % bd(adedges))
    print("  console-only both-dirs:  %d" % bd(coedges))
    print("  cmdargs-only both-dirs:  %d" % bd(caedges))
    print("  hcargs-only both-dirs:   %d" % bd(haedges))
    print("  rxdec2-only both-dirs:   %d" % bd(rdedges))
    print("  fwupd-only both-dirs:    %d" % bd(fwedges))
    print("  flashlock-only both-dirs: %d" % bd(fledges))
    print("  flashprog-only both-dirs: %d" % bd(fpedges))
    print("  i2cevt-only both-dirs:   %d" % bd(ieedges))
    print("  ccstate-only both-dirs:  %d" % bd(ccedges))
    print("  pdcmd-only both-dirs:    %d" % bd(pcedges))
    print("  hostpkt-only both-dirs:  %d" % bd(hpedges))
    print("  pdsoak-only both-dirs:   %d" % bd(psedges))
    print("  vdmtx-only both-dirs:    %d" % bd(vtedges))
    print("  debounce-only both-dirs: %d" % bd(dbedges))
    print("  reqcap-only both-dirs:   %d" % bd(rqedges))
    print("  srcseq-only both-dirs:   %d" % bd(ssedges))
    print("  panic-only both-dirs:    %d" % bd(pnedges))
    print("  panicinj-only both-dirs: %d" % bd(piedges))
    print("  dmairq-only both-dirs:   %d" % bd(dqedges))
    print("  usbevt-only both-dirs:   %d" % bd(uvedges))
    print("  gpioirq-only both-dirs:  %d" % bd(giedges))
    print("  smallisr-only both-dirs: %d" % bd(siedges))
    print("  tcpc-only both-dirs:     %d" % bd(tcedges))
    print("  sysinfo-only both-dirs:  %d" % bd(syedges))
    print("  consmisc-only both-dirs: %d" % bd(cmedges))
    print("  consmisc2-only both-dirs:%d" % bd(c2edges))
    print("  consmisc3-only both-dirs:%d" % bd(c3edges))
    print("  drpfree-only both-dirs:  %d" % bd(dfedges))
    print("  flashprot-only both-dirs:%d" % bd(fxedges))
    print("  audioacc-only both-dirs: %d" % bd(auedges))
    print("  lib-only both-dirs:      %d" % bd(liedges))
    print("  printf2-only both-dirs:  %d" % bd(p2edges))
    print("  spidma-only both-dirs:   %d" % bd(sdedges))
    print("  flashwp-only both-dirs:  %d" % bd(wpedges))
    print("  consmisc4-only both-dirs:%d" % bd(m4edges))
    print("  pdswap-only both-dirs:   %d" % bd(swedges))
    print("  flasherr-only both-dirs: %d" % bd(feedges))
    print("  flashfault-only both-dirs:%d" % bd(ffedges))
    print("  dmafault-only both-dirs: %d" % bd(dfedges2))
    print("  protcall-only both-dirs: %d" % bd(pcedges2))
    print("  spitcif-only both-dirs:  %d" % bd(stedges))
    print("  spibusy-only both-dirs:  %d" % bd(sbedges))
    print("  pdsink-only both-dirs:   %d" % bd(pkedges))
    print("  sysinfo2-only both-dirs: %d" % bd(si2edges))
    print("  gpioget-only both-dirs:  %d" % bd(ggedges))
    print("  hcver-only both-dirs:    %d" % bd(hvedges))
    print("  recpd-only both-dirs:    %d" % bd(rpedges))
    print("  drptoggle-only both-dirs:%d" % bd(dtedges))
    print("  pddbg-only both-dirs:    %d" % bd(pbedges))
    print("  conschar-only both-dirs: %d" % bd(ceedges))
    print("  flashprot2-only both-dirs:%d" % bd(f2edges))
    print("  optbclean-only both-dirs:%d" % bd(obedges))
    print("  pdfwupdate-only both-dirs:%d" % bd(fuedges))
    print("  pdsrc-only both-dirs:    %d" % bd(ps2edges))
    print("  pdbist-only both-dirs:   %d" % bd(biedges))
    print("  consargs-only both-dirs: %d" % bd(csaedges))
    print("  hcpkt2-only both-dirs:   %d" % bd(h2edges))
    print("  hccmd2-only both-dirs:   %d" % bd(h3edges))
    print("  i2cinit-only both-dirs:  %d" % bd(iiedges))
    print("  dmawait-only both-dirs:  %d" % bd(dwedges))
    print("  sweep+fuzz+pdstate add over campaign: +%d" % (len(both) - bd(cedges)))
    uncov = sorted(a for a in cond if a not in (set(taken) & set(nottaken)))
    with open(os.path.join(HERE, "cap_uncovered.txt"), "w") as f:
        for a in uncov:
            st = ("unreached" if a not in executed else
                  ("taken-only" if a in taken else ("nottaken-only" if a in nottaken else "?")))
            f.write("0x%08x %s\n" % (a, st))
    print("  wrote %d uncovered -> cap_uncovered.txt" % len(uncov))
    # Non-intrusive dump of the exact (cond, executed, edges) used above, so per-view reports
    # (e.g. cmdtable.py) consume byte-identical coverage data instead of re-deriving the union.
    with open(os.path.join(HERE, "tmp", "_combined.pkl"), "wb") as f:
        pickle.dump((cond, set(executed), set(edges)), f)
    print("  wrote tmp/_combined.pkl (cond/executed/edges snapshot)")


if __name__ == "__main__":
    main()
