#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: Apache-2.0
# Launch the gale eMMC auto-installer once boot completes (netifd up).
# Backgrounded so a hung install never blocks the serial shell.
START=99

boot() {
    /usr/sbin/gale-autoinstall > /dev/console 2>&1 &
}
