# SPDX-License-Identifier: Apache-2.0
"""Render the per-puck dnsmasq fragment (identity + install arming).

One combined dhcp-host line per puck — never two lines for the same MACs
(dnsmasq's duplicate-dhcp-host behavior is surprising and `--test` does
not catch it). The dhcp-boot line appears only when at least one puck is
armed; unarmed pucks get DHCP with no bootfile, which the netboot
firmware answers by falling back to the eMMC kernel.
"""

from __future__ import annotations

from gwifi_netboot.identity import Puck

BOOTFILE = "gale-installer.itb"

HEADER = (
    "# Generated by gwifi-netboot — puck identity + install arming. "
    "DO NOT EDIT.\n"
    "# Arming: `gwifi-netboot arm <puck>`; state in /var/lib/gwifi-netboot.\n"
)


def render_dnsmasq(pucks: list[Puck], armed: set[str]) -> str:
    """Render the dnsmasq conf fragment for the given identity + arming."""
    armed = {m.lower() for m in armed}
    lines = [HEADER.rstrip("\n")]
    any_armed = False
    for puck in sorted(pucks, key=lambda p: p.number):
        line = f"dhcp-host={puck.eth0},{puck.eth1},{puck.ip},{puck.name}"
        if puck.eth0 in armed or puck.eth1 in armed:
            line += ",set:install"
            any_armed = True
        lines.append(line)
    if any_armed:
        lines.append(f"dhcp-boot=tag:install,{BOOTFILE}")
    return "\n".join(lines) + "\n"
